[project]
name = "streamo"
version = "0.1.0"
description = "🚰 Stream audio to all services 🚰"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.57.0",
    "google-auth-oauthlib>=1.4.1",
    "numpy",
    "pillow>=12.3.0",
    "pydantic>=2",
    "reccy",
    "sounddevice",
    "tyro",
]

[project.scripts]
streamo = "streamo.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest",
    "pytest-regressions>=2.11.0",
    "pytest-xdist>=3.8.0",
    "pyupgrade>=3.21.2",
    "ruff",
    "ty>=0.0.78",
]

[tool.pytest.ini_options]
addopts = "-n 4 --dist=loadfile"

[tool.uv]
exclude-newer = "1 week"

[tool.uv.sources]
reccy = { git = "https://github.com/rec/reccy.git", branch = "main" }

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["B", "E", "F", "I"]
